add new OpenWeatherMap weather condition codes
Add new weather condition codes. Make the application more
resilient to the introduction of new weather condition codes in
the future: the application will use the English description of
the weather condition code instead of crashing with
"AttributeError: 'dict' object has no attribute 'has_key'".

Signed-off-by: Val Kulkov <val.kulkov@gmail.com>